/*
 * Samsung Exynos4 SoC series FIMC-IS slave interface driver
 *
 * exynos4 fimc-is helper functions
 *
 * Copyright (c) 2011 Samsung Electronics Co., Ltd
 * Contact: Younghwan Joo, <yhwan.joo@samsung.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 */
#include <linux/module.h>
#include <linux/kernel.h>
#include <linux/errno.h>
#include <linux/clk.h>
#include <linux/irq.h>
#include <linux/interrupt.h>
#include <linux/device.h>
#include <linux/platform_device.h>
#include <linux/slab.h>
#include <linux/io.h>
#include <linux/delay.h>
#include <linux/memory.h>
#include <linux/regulator/consumer.h>
#include <linux/pm_runtime.h>
#include <linux/videodev2.h>
#include <media/v4l2-subdev.h>
#include <linux/videodev2.h>
#include <linux/videodev2_samsung.h>

#include "fimc-is-core.h"
#include "fimc-is-regs.h"
#include "fimc-is-cmd.h"
#include "fimc-is-param.h"

#define ISP_STRGEN
/*
 Group 1. Interrupt
*/
void fimc_is_hw_set_intgr0_gd0(struct fimc_is_dev *dev)
{
	writel(INTGR0_INTGD0, dev->regs + INTGR0);
}

int fimc_is_hw_wait_intsr0_intsd0(struct fimc_is_dev *dev)
{
	u32 cfg = readl(dev->regs + INTSR0);
	u32 status = INTSR0_GET_INTSD0(cfg);
	while (status) {
		cfg = readl(dev->regs + INTSR0);
		status = INTSR0_GET_INTSD0(cfg);
	}
	return 0;
}

int fimc_is_fw_clear_irq1(struct fimc_is_dev *dev)
{
	u32 cfg = readl(dev->regs + INTSR1);

	writel(cfg, dev->regs + INTCR1);
	return 0;
}

int fimc_is_fw_clear_irq2(struct fimc_is_dev *dev)
{
	u32 cfg = readl(dev->regs + INTSR2);

	writel(cfg, dev->regs + INTCR2);
	return 0;
}

/*
 Group 2. Common
*/
void fimc_is_hw_open_sensor(struct fimc_is_dev *dev, u32 id, u32 scenario_id)
{
	dev->sensor_id = id;
	writel(HIC_OPEN_SENSOR, dev->regs + ISSR0);
	writel(dev->sensor_id, dev->regs + ISSR1);
	writel(dev->sensor_id, dev->regs + ISSR2);
	writel(scenario_id, dev->regs + ISSR3);
	fimc_is_hw_wait_intsr0_intsd0(dev);
	fimc_is_hw_set_intgr0_gd0(dev);
}

void fimc_is_hw_close_sensor(struct fimc_is_dev *dev, u32 id)
{
	if (dev->sensor_id == id) {
		writel(HIC_CLOSE_SENSOR, dev->regs + ISSR0);
		writel(dev->sensor_id, dev->regs + ISSR1);
		writel(dev->sensor_id, dev->regs + ISSR2);
		fimc_is_hw_wait_intsr0_intsd0(dev);
		fimc_is_hw_set_intgr0_gd0(dev);
	}
}

void fimc_is_hw_diable_wdt(struct fimc_is_dev *dev)
{
	writel(0x00008000, dev->regs + WDT);
}

void fimc_is_hw_set_lite(struct fimc_is_dev *dev, u32 width, u32 height)
{

	u32 cfg = readl(dev->regs_fimc_lite);
	cfg = cfg & 0x0000C000;
	cfg |= ((width+dev->sensor.offset_x)<<16);
	cfg |= (height+dev->sensor.offset_y);
	writel(cfg, dev->regs_fimc_lite);

	cfg = 0;
	cfg |= ((width+dev->sensor.offset_x));
	cfg |= (height+dev->sensor.offset_y)<<16;
	writel(cfg, dev->regs_fimc_lite+0x20);
}

void fimc_is_hw_io_init(struct fimc_is_dev *dev)
{
	void __iomem *reg_gpio3con;
	void __iomem *reg_gpm4con;
	/* 1. FIMC Lite0 setting - temp */

	int i;
	u32 cfg[16][2] = {
		{0x04, 0x00080008},
		{0x04, 0x000e0008},
		{0x04, 0x00100008},
		{0x04, 0x2b100008},
		{0x04, 0x2b100008},
		{0x10, 0x4000c000},
		{0x10, 0x00000000},
		{0x04, 0x2b100008},
		{0x04, 0x2b100008},
		{0x00, 0x028c01e8},
		{0x10, 0x00000000},
		{0x30, 0x42000000},
		{0x20, 0x01e8028c},
		{0x04, 0x2b100048},
		{0xfc, 0x00000000},
		{0x08, 0x80000000},
	};
	for (i = 0; i < 16; i++)
		writel(cfg[i][1], dev->regs_fimc_lite + cfg[i][0]);

	/* 2. UART setting for FIMC-IS */
	reg_gpio3con = ioremap(0x110002c0, 0x4);
	writel(0x33330000, reg_gpio3con);
	iounmap(reg_gpio3con);
	reg_gpio3con = NULL;
	/* 3. GPIO setting for FIMC-IS */
	reg_gpm4con = ioremap(0x110002e0, 0x4);
	writel(0x00000022, reg_gpm4con);
	iounmap(reg_gpm4con);
	reg_gpm4con = NULL;
}

void fimc_is_hw_reset(struct fimc_is_dev *dev)
{
	u32 cfg;
	void __iomem *reg_isp_arm_option;
	cfg = dev->mem.base;

	writel(cfg, dev->regs + BBOAR);

	reg_isp_arm_option = ioremap(0x10022288, 0x4);
	writel(0x00018000, reg_isp_arm_option);
	iounmap(reg_isp_arm_option);
	reg_isp_arm_option = NULL;
}

void fimc_is_hw_set_sensor_num(struct fimc_is_dev *dev)
{
	u32 cfg;
	writel(ISR_DONE, dev->regs + ISSR0);
	cfg = dev->sensor_id;
	writel(cfg, dev->regs + ISSR1);
	/* param 1 */
	writel(IHC_GET_SENSOR_NUMBER, dev->regs + ISSR2);
	/* param 2 */
	cfg = dev->sensor_num;
	writel(cfg, dev->regs + ISSR3);
}

int fimc_is_hw_get_sensor_num(struct fimc_is_dev *dev)
{
	u32 cfg = readl(dev->regs + ISSR11);
	if (dev->sensor_num == cfg)
		return 0;
	else
		return cfg;
}

int fimc_is_hw_set_param(struct fimc_is_dev *dev)
{
	writel(HIC_SET_PARAMETER, dev->regs + ISSR0);
	writel(dev->sensor_id, dev->regs + ISSR1);

	writel(dev->scenario_id, dev->regs + ISSR2);

	writel(atomic_read(&dev->p_region_num), dev->regs + ISSR3);
	writel(dev->p_region_index1, dev->regs + ISSR4);
	writel(dev->p_region_index2, dev->regs + ISSR5);
	fimc_is_hw_wait_intsr0_intsd0(dev);
	fimc_is_hw_set_intgr0_gd0(dev);
	return 0;
}

int fimc_is_hw_get_param(struct fimc_is_dev *dev, u16 offset)
{
	dev->i2h_cmd.num_valid_args = offset;
	switch (offset) {
	case 1:
		dev->i2h_cmd.arg[0] = readl(dev->regs + ISSR12);
		dev->i2h_cmd.arg[1] = 0;
		dev->i2h_cmd.arg[2] = 0;
		dev->i2h_cmd.arg[3] = 0;
		break;
	case 2:
		dev->i2h_cmd.arg[0] = readl(dev->regs + ISSR12);
		dev->i2h_cmd.arg[1] = readl(dev->regs + ISSR13);
		dev->i2h_cmd.arg[2] = 0;
		dev->i2h_cmd.arg[3] = 0;
		break;
	case 3:
		dev->i2h_cmd.arg[0] = readl(dev->regs + ISSR12);
		dev->i2h_cmd.arg[1] = readl(dev->regs + ISSR13);
		dev->i2h_cmd.arg[2] = readl(dev->regs + ISSR14);
		dev->i2h_cmd.arg[3] = 0;
		break;
	case 4:
		dev->i2h_cmd.arg[0] = readl(dev->regs + ISSR12);
		dev->i2h_cmd.arg[1] = readl(dev->regs + ISSR13);
		dev->i2h_cmd.arg[2] = readl(dev->regs + ISSR14);
		dev->i2h_cmd.arg[3] = readl(dev->regs + ISSR15);
		break;
	default:
		return -EINVAL;
	}

	return 0;
}

void fimc_is_hw_set_stream(struct fimc_is_dev *dev, int on)
{
	if (on) {
		writel(HIC_STREAM_ON, dev->regs + ISSR0);
		writel(dev->sensor_id, dev->regs + ISSR1);
		fimc_is_hw_wait_intsr0_intsd0(dev);
		fimc_is_hw_set_intgr0_gd0(dev);
	} else {
		writel(HIC_STREAM_OFF, dev->regs + ISSR0);
		writel(dev->sensor_id, dev->regs + ISSR1);
		fimc_is_hw_wait_intsr0_intsd0(dev);
		fimc_is_hw_set_intgr0_gd0(dev);
	}
}

void fimc_is_hw_change_mode(struct fimc_is_dev *dev, int val)
{
	switch (val) {
	case IS_MODE_PREVIEW_STILL:
		dev->scenario_id = ISS_PREVIEW_STILL;
		clear_bit(IS_ST_RUN, &dev->state);
		set_bit(IS_ST_CHANGE_MODE, &dev->state);
		writel(HIC_PREVIEW_STILL, dev->regs + ISSR0);
		writel(dev->sensor_id, dev->regs + ISSR1);
		fimc_is_hw_wait_intsr0_intsd0(dev);
		fimc_is_hw_set_intgr0_gd0(dev);
		break;
	case IS_MODE_PREVIEW_VIDEO:
		dev->scenario_id = ISS_PREVIEW_VIDEO;
		clear_bit(IS_ST_RUN, &dev->state);
		set_bit(IS_ST_CHANGE_MODE, &dev->state);
		writel(HIC_PREVIEW_VIDEO, dev->regs + ISSR0);
		writel(dev->sensor_id, dev->regs + ISSR1);
		fimc_is_hw_wait_intsr0_intsd0(dev);
		fimc_is_hw_set_intgr0_gd0(dev);
		break;
	case IS_MODE_CAPTURE_STILL:
		dev->scenario_id = ISS_CAPTURE_STILL;
		clear_bit(IS_ST_RUN, &dev->state);
		set_bit(IS_ST_CHANGE_MODE, &dev->state);
		writel(HIC_CAPTURE_STILL, dev->regs + ISSR0);
		writel(dev->sensor_id, dev->regs + ISSR1);
		fimc_is_hw_wait_intsr0_intsd0(dev);
		fimc_is_hw_set_intgr0_gd0(dev);
		break;
	case IS_MODE_CAPTURE_VIDEO:
		dev->scenario_id = ISS_CAPTURE_VIDEO;
		clear_bit(IS_ST_RUN, &dev->state);
		set_bit(IS_ST_CHANGE_MODE, &dev->state);
		writel(HIC_CAPTURE_VIDEO, dev->regs + ISSR0);
		writel(dev->sensor_id, dev->regs + ISSR1);
		fimc_is_hw_wait_intsr0_intsd0(dev);
		fimc_is_hw_set_intgr0_gd0(dev);
		break;
	}
}
/*
 Group 3. Initial setting
*/
void fimc_is_hw_set_init(struct fimc_is_dev *dev)
{
	switch (dev->scenario_id) {
	case ISS_PREVIEW_STILL:
		/* ISP */
		IS_ISP_SET_PARAM_CONTROL_CMD(dev, CONTROL_COMMAND_START);
		IS_ISP_SET_PARAM_CONTROL_BYPASS(dev, CONTROL_BYPASS_DISABLE);
		IS_ISP_SET_PARAM_CONTROL_ERR(dev, CONTROL_ERROR_NO);
		IS_SET_PARAM_BIT(dev, PARAM_ISP_CONTROL);
		IS_INC_PARAM_NUM(dev);
		IS_ISP_SET_PARAM_OTF_INPUT_CMD(dev, OTF_INPUT_COMMAND_ENABLE);
		IS_ISP_SET_PARAM_OTF_INPUT_WIDTH(dev, 1920);
		IS_ISP_SET_PARAM_OTF_INPUT_HEIGHT(dev, 1080);
#ifndef ISP_STRGEN
		IS_ISP_SET_PARAM_OTF_INPUT_FORMAT(dev, OTF_INPUT_FORMAT_BAYER);
#else
		IS_ISP_SET_PARAM_OTF_INPUT_FORMAT(dev,
			OTF_INPUT_FORMAT_STRGEN_COLORBAR_BAYER);
#endif
		IS_ISP_SET_PARAM_OTF_INPUT_BITWIDTH(dev,
			OTF_INPUT_BIT_WIDTH_10BIT);
		IS_ISP_SET_PARAM_OTF_INPUT_ORDER(dev,
			OTF_INPUT_ORDER_BAYER_GR_BG);
		IS_ISP_SET_PARAM_OTF_INPUT_ERR(dev, OTF_INPUT_ERROR_NO);
		IS_SET_PARAM_BIT(dev, PARAM_ISP_OTF_INPUT);
		IS_INC_PARAM_NUM(dev);
		IS_ISP_SET_PARAM_DMA_INPUT1_CMD(dev,
			DMA_INPUT_COMMAND_DISABLE);
		IS_ISP_SET_PARAM_DMA_INPUT1_WIDTH(dev, 0);
		IS_ISP_SET_PARAM_DMA_INPUT1_HEIGHT(dev, 0);
		IS_ISP_SET_PARAM_DMA_INPUT1_FORMAT(dev, 0);
		IS_ISP_SET_PARAM_DMA_INPUT1_BITWIDTH(dev, 0);
		IS_ISP_SET_PARAM_DMA_INPUT1_PLANE(dev, 0);
		IS_ISP_SET_PARAM_DMA_INPUT1_ORDER(dev, 0);
		IS_ISP_SET_PARAM_DMA_INPUT1_BUFFERNUM(dev, 0);
		IS_ISP_SET_PARAM_DMA_INPUT1_BUFFERADDR(dev, 0);
		IS_ISP_SET_PARAM_DMA_INPUT1_ERR(dev, 0);
		IS_SET_PARAM_BIT(dev, PARAM_ISP_DMA1_INPUT);
		IS_INC_PARAM_NUM(dev);
		IS_ISP_SET_PARAM_DMA_INPUT2_CMD(dev,
			DMA_INPUT_COMMAND_DISABLE);
		IS_ISP_SET_PARAM_DMA_INPUT2_WIDTH(dev, 0);
		IS_ISP_SET_PARAM_DMA_INPUT2_HEIGHT(dev, 0);
		IS_ISP_SET_PARAM_DMA_INPUT2_FORMAT(dev, 0);
		IS_ISP_SET_PARAM_DMA_INPUT2_BITWIDTH(dev, 0);
		IS_ISP_SET_PARAM_DMA_INPUT2_PLANE(dev, 0);
		IS_ISP_SET_PARAM_DMA_INPUT2_ORDER(dev, 0);
		IS_ISP_SET_PARAM_DMA_INPUT2_BUFFERNUM(dev, 0);
		IS_ISP_SET_PARAM_DMA_INPUT2_BUFFERADDR(dev, 0);
		IS_ISP_SET_PARAM_DMA_INPUT2_ERR(dev, 0);
		IS_SET_PARAM_BIT(dev, PARAM_ISP_DMA2_INPUT);
		IS_INC_PARAM_NUM(dev);
		IS_ISP_SET_PARAM_AF_CMD(dev, ISP_AF_COMMAND_SET_FOCUSMODE);
		IS_ISP_SET_PARAM_AF_MODE(dev, ISP_AF_MODE_AUTO);
		IS_ISP_SET_PARAM_AF_FACE(dev, ISP_AF_FACE_DISABLE);
		IS_ISP_SET_PARAM_AF_CONTINUOUS(dev, ISP_AF_CONTINUOUS_DISABLE);
		IS_ISP_SET_PARAM_AF_WIN_POS_X(dev, 0);
		IS_ISP_SET_PARAM_AF_WIN_POS_Y(dev, 0);
		IS_ISP_SET_PARAM_AF_WIN_WIDTH(dev, 0);
		IS_ISP_SET_PARAM_AF_WIN_HEIGHT(dev, 0);
		IS_ISP_SET_PARAM_AF_ERR(dev, ISP_AF_ERROR_NO);
		IS_SET_PARAM_BIT(dev, PARAM_ISP_AF);
		IS_INC_PARAM_NUM(dev);
		IS_ISP_SET_PARAM_FLASH_CMD(dev,
			ISP_FLASH_COMMAND_DISABLE);
		IS_ISP_SET_PARAM_FLASH_REDEYE(dev,
			ISP_FLASH_REDEYE_DISABLE);
		IS_ISP_SET_PARAM_FLASH_ERR(dev, ISP_FLASH_ERROR_NO);
		IS_SET_PARAM_BIT(dev, PARAM_ISP_FLASH);
		IS_INC_PARAM_NUM(dev);
		IS_ISP_SET_PARAM_AWB_CMD(dev, ISP_AWB_COMMAND_AUTO);
		IS_ISP_SET_PARAM_AWB_ILLUMINATION(dev, 0);
		IS_ISP_SET_PARAM_AWB_ERR(dev, ISP_AWB_ERROR_NO);
		IS_SET_PARAM_BIT(dev, PARAM_ISP_AWB);
		IS_INC_PARAM_NUM(dev);
		IS_ISP_SET_PARAM_EFFECT_CMD(dev, ISP_IMAGE_EFFECT_DISABLE);
		IS_ISP_SET_PARAM_EFFECT_ERR(dev, ISP_IMAGE_EFFECT_ERROR_NO);
		IS_SET_PARAM_BIT(dev, PARAM_ISP_IMAGE_EFFECT);
		IS_INC_PARAM_NUM(dev);
		IS_ISP_SET_PARAM_ISO_CMD(dev, ISP_ISO_COMMAND_AUTO);
		IS_ISP_SET_PARAM_ISO_VALUE(dev, 0);
		IS_ISP_SET_PARAM_ISO_ERR(dev, ISP_ISO_ERROR_NO);
		IS_SET_PARAM_BIT(dev, PARAM_ISP_ISO);
		IS_INC_PARAM_NUM(dev);
		IS_ISP_SET_PARAM_ADJUST_CMD(dev,
			ISP_ADJUST_COMMAND_AUTOCONTRAST);
		IS_ISP_SET_PARAM_ADJUST_CONTRAST(dev, 0);
		IS_ISP_SET_PARAM_ADJUST_SATURATION(dev, 0);
		IS_ISP_SET_PARAM_ADJUST_SHARPNESS(dev, 0);
		IS_ISP_SET_PARAM_ADJUST_EXPOSURE(dev, 0);
		IS_ISP_SET_PARAM_ADJUST_BRIGHTNESS(dev, 0);
		IS_ISP_SET_PARAM_ADJUST_HUE(dev, 0);
		IS_ISP_SET_PARAM_ADJUST_ERR(dev, ISP_ADJUST_ERROR_NO);
		IS_SET_PARAM_BIT(dev, PARAM_ISP_ADJUST);
		IS_INC_PARAM_NUM(dev);
		IS_ISP_SET_PARAM_METERING_CMD(dev,
			ISP_METERING_COMMAND_MATRIX);
		IS_ISP_SET_PARAM_METERING_WIN_POS_X(dev, 0);
		IS_ISP_SET_PARAM_METERING_WIN_POS_Y(dev, 0);
		IS_ISP_SET_PARAM_METERING_WIN_WIDTH(dev, 1920);
		IS_ISP_SET_PARAM_METERING_WIN_HEIGHT(dev, 1080);
		IS_ISP_SET_PARAM_METERING_ERR(dev,
			ISP_METERING_ERROR_NO);
		IS_SET_PARAM_BIT(dev, PARAM_ISP_METERING);
		IS_INC_PARAM_NUM(dev);
		IS_ISP_SET_PARAM_AFC_CMD(dev, ISP_AFC_COMMAND_AUTO);
		IS_ISP_SET_PARAM_AFC_MANUAL(dev, 0);
		IS_ISP_SET_PARAM_AFC_ERR(dev, ISP_AFC_ERROR_NO);
		IS_SET_PARAM_BIT(dev, PARAM_ISP_AFC);
		IS_INC_PARAM_NUM(dev);
		IS_ISP_SET_PARAM_OTF_OUTPUT_CMD(dev,
			OTF_OUTPUT_COMMAND_ENABLE);
		IS_ISP_SET_PARAM_OTF_OUTPUT_WIDTH(dev, 1920);
		IS_ISP_SET_PARAM_OTF_OUTPUT_HEIGHT(dev, 1080);
		IS_ISP_SET_PARAM_OTF_OUTPUT_FORMAT(dev,
			OTF_OUTPUT_FORMAT_YUV444);
		IS_ISP_SET_PARAM_OTF_OUTPUT_BITWIDTH(dev,
			OTF_OUTPUT_BIT_WIDTH_12BIT);
		IS_ISP_SET_PARAM_OTF_OUTPUT_ORDER(dev,
			OTF_OUTPUT_ORDER_BAYER_GR_BG);
		IS_ISP_SET_PARAM_OTF_OUTPUT_ERR(dev,
			OTF_OUTPUT_ERROR_NO);
		IS_SET_PARAM_BIT(dev, PARAM_ISP_OTF_OUTPUT);
		IS_INC_PARAM_NUM(dev);
		IS_ISP_SET_PARAM_DMA_OUTPUT1_CMD(dev,
			DMA_OUTPUT_COMMAND_DISABLE);
		IS_ISP_SET_PARAM_DMA_OUTPUT1_WIDTH(dev, 0);
		IS_ISP_SET_PARAM_DMA_OUTPUT1_HEIGHT(dev, 0);
		IS_ISP_SET_PARAM_DMA_OUTPUT1_FORMAT(dev, 0);
		IS_ISP_SET_PARAM_DMA_OUTPUT1_BITWIDTH(dev, 0);
		IS_ISP_SET_PARAM_DMA_OUTPUT1_PLANE(dev, 0);
		IS_ISP_SET_PARAM_DMA_OUTPUT1_ORDER(dev, 0);
		IS_ISP_SET_PARAM_DMA_OUTPUT1_BUFFER_NUMBER(dev, 0);
		IS_ISP_SET_PARAM_DMA_OUTPUT1_BUFFER_ADDRESS(dev, 0);
		IS_ISP_SET_PARAM_DMA_OUTPUT1_ERR(dev,
			DMA_OUTPUT_ERROR_NO);
		IS_SET_PARAM_BIT(dev, PARAM_ISP_DMA1_OUTPUT);
		IS_INC_PARAM_NUM(dev);
		IS_ISP_SET_PARAM_DMA_OUTPUT2_CMD(dev,
			DMA_OUTPUT_COMMAND_DISABLE);
		IS_ISP_SET_PARAM_DMA_OUTPUT2_WIDTH(dev, 0);
		IS_ISP_SET_PARAM_DMA_OUTPUT2_HEIGHT(dev, 0);
		IS_ISP_SET_PARAM_DMA_OUTPUT2_FORMAT(dev, 0);
		IS_ISP_SET_PARAM_DMA_OUTPUT2_BITWIDTH(dev, 0);
		IS_ISP_SET_PARAM_DMA_OUTPUT2_PLANE(dev, 0);
		IS_ISP_SET_PARAM_DMA_OUTPUT2_ORDER(dev, 0);
		IS_ISP_SET_PARAM_DMA_OUTPUT2_BUFFER_NUMBER(dev, 0);
		IS_ISP_SET_PARAM_DMA_OUTPUT2_BUFFER_ADDRESS(dev, 0);
		IS_ISP_SET_PARAM_DMA_OUTPUT2_ERR(dev,
			DMA_OUTPUT_ERROR_NO);
		IS_SET_PARAM_BIT(dev, PARAM_ISP_DMA2_OUTPUT);
		IS_INC_PARAM_NUM(dev);

		/* DRC */
		IS_DRC_SET_PARAM_CONTROL_CMD(dev, CONTROL_COMMAND_START);
		IS_DRC_SET_PARAM_CONTROL_BYPASS(dev, CONTROL_BYPASS_ENABLE);
		IS_DRC_SET_PARAM_CONTROL_ERR(dev, CONTROL_ERROR_NO);
		IS_SET_PARAM_BIT(dev, PARAM_DRC_CONTROL);
		IS_INC_PARAM_NUM(dev);
		IS_DRC_SET_PARAM_OTF_INPUT_CMD(dev, OTF_INPUT_COMMAND_ENABLE);
		IS_DRC_SET_PARAM_OTF_INPUT_WIDTH(dev, 1920);
		IS_DRC_SET_PARAM_OTF_INPUT_HEIGHT(dev, 1080);
		IS_DRC_SET_PARAM_OTF_INPUT_FORMAT(dev,
			OTF_INPUT_FORMAT_YUV444);
		IS_DRC_SET_PARAM_OTF_INPUT_BITWIDTH(dev,
			OTF_INPUT_BIT_WIDTH_12BIT);
		IS_DRC_SET_PARAM_OTF_INPUT_ORDER(dev,
			OTF_INPUT_ORDER_BAYER_GR_BG);
		IS_DRC_SET_PARAM_OTF_INPUT_ERR(dev, OTF_INPUT_ERROR_NO);
		IS_SET_PARAM_BIT(dev, PARAM_DRC_OTF_INPUT);
		IS_INC_PARAM_NUM(dev);
		IS_DRC_SET_PARAM_DMA_INPUT_CMD(dev, DMA_INPUT_COMMAND_DISABLE);
		IS_DRC_SET_PARAM_DMA_INPUT_WIDTH(dev, 1920);
		IS_DRC_SET_PARAM_DMA_INPUT_HEIGHT(dev, 1080);
		IS_DRC_SET_PARAM_DMA_INPUT_FORMAT(dev,
			OTF_OUTPUT_FORMAT_YUV444);
		IS_DRC_SET_PARAM_DMA_INPUT_BITWIDTH(dev,
			OTF_OUTPUT_BIT_WIDTH_8BIT);
		IS_DRC_SET_PARAM_DMA_INPUT_PLANE(dev, 0);
		IS_DRC_SET_PARAM_DMA_INPUT_ORDER(dev, 0);
		IS_DRC_SET_PARAM_DMA_INPUT_BUFFERNUM(dev, 0);
		IS_DRC_SET_PARAM_DMA_INPUT_BUFFERADDR(dev, 0);
		IS_DRC_SET_PARAM_DMA_INPUT_ERR(dev, 0);
		IS_SET_PARAM_BIT(dev, PARAM_DRC_DMA_INPUT);
		IS_INC_PARAM_NUM(dev);
		IS_DRC_SET_PARAM_OTF_OUTPUT_CMD(dev,
			OTF_OUTPUT_COMMAND_ENABLE);
		IS_DRC_SET_PARAM_OTF_OUTPUT_WIDTH(dev, 1920);
		IS_DRC_SET_PARAM_OTF_OUTPUT_HEIGHT(dev, 1080);
		IS_DRC_SET_PARAM_OTF_OUTPUT_FORMAT(dev,
			OTF_OUTPUT_FORMAT_YUV444);
		IS_DRC_SET_PARAM_OTF_OUTPUT_BITWIDTH(dev,
			OTF_OUTPUT_BIT_WIDTH_8BIT);
		IS_DRC_SET_PARAM_OTF_OUTPUT_ORDER(dev,
			OTF_OUTPUT_ORDER_BAYER_GR_BG);
		IS_DRC_SET_PARAM_OTF_OUTPUT_ERR(dev, OTF_OUTPUT_ERROR_NO);
		IS_SET_PARAM_BIT(dev, PARAM_DRC_OTF_OUTPUT);
		IS_INC_PARAM_NUM(dev);

		/* FD */
		IS_FD_SET_PARAM_CONTROL_CMD(dev, CONTROL_COMMAND_STOP);
		IS_FD_SET_PARAM_CONTROL_BYPASS(dev, CONTROL_BYPASS_ENABLE);
		IS_FD_SET_PARAM_CONTROL_ERR(dev, CONTROL_ERROR_NO);
		IS_SET_PARAM_BIT(dev, PARAM_FD_CONTROL);
		IS_INC_PARAM_NUM(dev);
		IS_FD_SET_PARAM_OTF_INPUT_CMD(dev,
			OTF_INPUT_COMMAND_ENABLE);
		IS_FD_SET_PARAM_OTF_INPUT_WIDTH(dev, 1920);
		IS_FD_SET_PARAM_OTF_INPUT_HEIGHT(dev, 1080);
		IS_FD_SET_PARAM_OTF_INPUT_FORMAT(dev,
			OTF_INPUT_FORMAT_YUV444);
		IS_FD_SET_PARAM_OTF_INPUT_BITWIDTH(dev,
			OTF_INPUT_BIT_WIDTH_8BIT);
		IS_FD_SET_PARAM_OTF_INPUT_ORDER(dev,
			OTF_INPUT_ORDER_BAYER_GR_BG);
		IS_FD_SET_PARAM_OTF_INPUT_ERR(dev, OTF_INPUT_ERROR_NO);
		IS_SET_PARAM_BIT(dev, PARAM_FD_OTF_INPUT);
		IS_INC_PARAM_NUM(dev);
		IS_FD_SET_PARAM_DMA_INPUT_CMD(dev,
			DMA_INPUT_COMMAND_DISABLE);
		IS_FD_SET_PARAM_DMA_INPUT_WIDTH(dev, 0);
		IS_FD_SET_PARAM_DMA_INPUT_HEIGHT(dev, 0);
		IS_FD_SET_PARAM_DMA_INPUT_FORMAT(dev, 0);
		IS_FD_SET_PARAM_DMA_INPUT_BITWIDTH(dev, 0);
		IS_FD_SET_PARAM_DMA_INPUT_PLANE(dev, 0);
		IS_FD_SET_PARAM_DMA_INPUT_ORDER(dev, 0);
		IS_FD_SET_PARAM_DMA_INPUT_BUFFERNUM(dev, 0);
		IS_FD_SET_PARAM_DMA_INPUT_BUFFERADDR(dev, 0);
		IS_FD_SET_PARAM_DMA_INPUT_ERR(dev, 0);
		IS_SET_PARAM_BIT(dev, PARAM_FD_DMA_INPUT);
		IS_INC_PARAM_NUM(dev);
		IS_FD_SET_PARAM_FDCONTROL_MAX_NUMBER(dev, 10);
		IS_FD_SET_PARAM_FDCONTROL_ERR(dev, FD_ERROR_NO);
		IS_SET_PARAM_BIT(dev, PARAM_FD_FD);
		IS_INC_PARAM_NUM(dev);
		break;

	case ISS_PREVIEW_VIDEO:
		/* ISP */
		IS_ISP_SET_PARAM_CONTROL_CMD(dev, CONTROL_COMMAND_START);
		IS_ISP_SET_PARAM_CONTROL_BYPASS(dev, CONTROL_BYPASS_DISABLE);
		IS_ISP_SET_PARAM_CONTROL_ERR(dev, CONTROL_ERROR_NO);
		IS_SET_PARAM_BIT(dev, PARAM_ISP_CONTROL);
		IS_INC_PARAM_NUM(dev);
		IS_ISP_SET_PARAM_OTF_INPUT_CMD(dev, OTF_INPUT_COMMAND_ENABLE);
		IS_ISP_SET_PARAM_OTF_INPUT_WIDTH(dev, 640);
		IS_ISP_SET_PARAM_OTF_INPUT_HEIGHT(dev, 480);
#ifndef ISP_STRGEN
		IS_ISP_SET_PARAM_OTF_INPUT_FORMAT(dev, OTF_INPUT_FORMAT_BAYER);
#else
		IS_ISP_SET_PARAM_OTF_INPUT_FORMAT(dev,
			OTF_INPUT_FORMAT_STRGEN_COLORBAR_BAYER);
#endif
		IS_ISP_SET_PARAM_OTF_INPUT_BITWIDTH(dev,
			OTF_INPUT_BIT_WIDTH_10BIT);
		IS_ISP_SET_PARAM_OTF_INPUT_ORDER(dev,
			OTF_INPUT_ORDER_BAYER_GR_BG);
		IS_ISP_SET_PARAM_OTF_INPUT_ERR(dev, OTF_INPUT_ERROR_NO);
		IS_SET_PARAM_BIT(dev, PARAM_ISP_OTF_INPUT);
		IS_INC_PARAM_NUM(dev);
		IS_ISP_SET_PARAM_DMA_INPUT1_CMD(dev,
			DMA_INPUT_COMMAND_DISABLE);
		IS_ISP_SET_PARAM_DMA_INPUT1_WIDTH(dev, 0);
		IS_ISP_SET_PARAM_DMA_INPUT1_HEIGHT(dev, 0);
		IS_ISP_SET_PARAM_DMA_INPUT1_FORMAT(dev, 0);
		IS_ISP_SET_PARAM_DMA_INPUT1_BITWIDTH(dev, 0);
		IS_ISP_SET_PARAM_DMA_INPUT1_PLANE(dev, 0);
		IS_ISP_SET_PARAM_DMA_INPUT1_ORDER(dev, 0);
		IS_ISP_SET_PARAM_DMA_INPUT1_BUFFERNUM(dev, 0);
		IS_ISP_SET_PARAM_DMA_INPUT1_BUFFERADDR(dev, 0);
		IS_ISP_SET_PARAM_DMA_INPUT1_ERR(dev, 0);
		IS_SET_PARAM_BIT(dev, PARAM_ISP_DMA1_INPUT);
		IS_INC_PARAM_NUM(dev);
		IS_ISP_SET_PARAM_DMA_INPUT2_CMD(dev,
			DMA_INPUT_COMMAND_DISABLE);
		IS_ISP_SET_PARAM_DMA_INPUT2_WIDTH(dev, 0);
		IS_ISP_SET_PARAM_DMA_INPUT2_HEIGHT(dev, 0);
		IS_ISP_SET_PARAM_DMA_INPUT2_FORMAT(dev, 0);
		IS_ISP_SET_PARAM_DMA_INPUT2_BITWIDTH(dev, 0);
		IS_ISP_SET_PARAM_DMA_INPUT2_PLANE(dev, 0);
		IS_ISP_SET_PARAM_DMA_INPUT2_ORDER(dev, 0);
		IS_ISP_SET_PARAM_DMA_INPUT2_BUFFERNUM(dev, 0);
		IS_ISP_SET_PARAM_DMA_INPUT2_BUFFERADDR(dev, 0);
		IS_ISP_SET_PARAM_DMA_INPUT2_ERR(dev, 0);
		IS_SET_PARAM_BIT(dev, PARAM_ISP_DMA2_INPUT);
		IS_INC_PARAM_NUM(dev);
		IS_ISP_SET_PARAM_AF_CMD(dev, ISP_AF_COMMAND_SET_FOCUSMODE);
		IS_ISP_SET_PARAM_AF_MODE(dev, ISP_AF_MODE_AUTO);
		IS_ISP_SET_PARAM_AF_FACE(dev, ISP_AF_FACE_DISABLE);
		IS_ISP_SET_PARAM_AF_CONTINUOUS(dev, ISP_AF_CONTINUOUS_DISABLE);
		IS_ISP_SET_PARAM_AF_WIN_POS_X(dev, 0);
		IS_ISP_SET_PARAM_AF_WIN_POS_Y(dev, 0);
		IS_ISP_SET_PARAM_AF_WIN_WIDTH(dev, 0);
		IS_ISP_SET_PARAM_AF_WIN_HEIGHT(dev, 0);
		IS_ISP_SET_PARAM_AF_ERR(dev, ISP_AF_ERROR_NO);
		IS_SET_PARAM_BIT(dev, PARAM_ISP_AF);
		IS_INC_PARAM_NUM(dev);
		IS_ISP_SET_PARAM_FLASH_CMD(dev,
			ISP_FLASH_COMMAND_DISABLE);
		IS_ISP_SET_PARAM_FLASH_REDEYE(dev,
			ISP_FLASH_REDEYE_DISABLE);
		IS_ISP_SET_PARAM_FLASH_ERR(dev, ISP_FLASH_ERROR_NO);
		IS_SET_PARAM_BIT(dev, PARAM_ISP_FLASH);
		IS_INC_PARAM_NUM(dev);
		IS_ISP_SET_PARAM_AWB_CMD(dev, ISP_AWB_COMMAND_AUTO);
		IS_ISP_SET_PARAM_AWB_ILLUMINATION(dev, 0);
		IS_ISP_SET_PARAM_AWB_ERR(dev, ISP_AWB_ERROR_NO);
		IS_SET_PARAM_BIT(dev, PARAM_ISP_AWB);
		IS_INC_PARAM_NUM(dev);
		IS_ISP_SET_PARAM_EFFECT_CMD(dev, ISP_IMAGE_EFFECT_DISABLE);
		IS_ISP_SET_PARAM_EFFECT_ERR(dev, ISP_IMAGE_EFFECT_ERROR_NO);
		IS_SET_PARAM_BIT(dev, PARAM_ISP_IMAGE_EFFECT);
		IS_INC_PARAM_NUM(dev);
		IS_ISP_SET_PARAM_ISO_CMD(dev, ISP_ISO_COMMAND_AUTO);
		IS_ISP_SET_PARAM_ISO_VALUE(dev, 0);
		IS_ISP_SET_PARAM_ISO_ERR(dev, ISP_ISO_ERROR_NO);
		IS_SET_PARAM_BIT(dev, PARAM_ISP_ISO);
		IS_INC_PARAM_NUM(dev);
		IS_ISP_SET_PARAM_ADJUST_CMD(dev,
			ISP_ADJUST_COMMAND_AUTOCONTRAST);
		IS_ISP_SET_PARAM_ADJUST_CONTRAST(dev, 0);
		IS_ISP_SET_PARAM_ADJUST_SATURATION(dev, 0);
		IS_ISP_SET_PARAM_ADJUST_SHARPNESS(dev, 0);
		IS_ISP_SET_PARAM_ADJUST_EXPOSURE(dev, 0);
		IS_ISP_SET_PARAM_ADJUST_BRIGHTNESS(dev, 0);
		IS_ISP_SET_PARAM_ADJUST_HUE(dev, 0);
		IS_ISP_SET_PARAM_ADJUST_ERR(dev, ISP_ADJUST_ERROR_NO);
		IS_SET_PARAM_BIT(dev, PARAM_ISP_ADJUST);
		IS_INC_PARAM_NUM(dev);
		IS_ISP_SET_PARAM_METERING_CMD(dev,
			ISP_METERING_COMMAND_MATRIX);
		IS_ISP_SET_PARAM_METERING_WIN_POS_X(dev, 0);
		IS_ISP_SET_PARAM_METERING_WIN_POS_Y(dev, 0);
		IS_ISP_SET_PARAM_METERING_WIN_WIDTH(dev, 640);
		IS_ISP_SET_PARAM_METERING_WIN_HEIGHT(dev, 480);
		IS_ISP_SET_PARAM_METERING_ERR(dev,
			ISP_METERING_ERROR_NO);
		IS_SET_PARAM_BIT(dev, PARAM_ISP_METERING);
		IS_INC_PARAM_NUM(dev);
		IS_ISP_SET_PARAM_AFC_CMD(dev, ISP_AFC_COMMAND_AUTO);
		IS_ISP_SET_PARAM_AFC_MANUAL(dev, 0);
		IS_ISP_SET_PARAM_AFC_ERR(dev, ISP_AFC_ERROR_NO);
		IS_SET_PARAM_BIT(dev, PARAM_ISP_AFC);
		IS_INC_PARAM_NUM(dev);
		IS_ISP_SET_PARAM_OTF_OUTPUT_CMD(dev,
			OTF_OUTPUT_COMMAND_ENABLE);
		IS_ISP_SET_PARAM_OTF_OUTPUT_WIDTH(dev, 640);
		IS_ISP_SET_PARAM_OTF_OUTPUT_HEIGHT(dev, 480);
		IS_ISP_SET_PARAM_OTF_OUTPUT_FORMAT(dev,
			OTF_OUTPUT_FORMAT_YUV444);
		IS_ISP_SET_PARAM_OTF_OUTPUT_BITWIDTH(dev,
			OTF_OUTPUT_BIT_WIDTH_12BIT);
		IS_ISP_SET_PARAM_OTF_OUTPUT_ORDER(dev,
			OTF_OUTPUT_ORDER_BAYER_GR_BG);
		IS_ISP_SET_PARAM_OTF_OUTPUT_ERR(dev,
			OTF_OUTPUT_ERROR_NO);
		IS_SET_PARAM_BIT(dev, PARAM_ISP_OTF_OUTPUT);
		IS_INC_PARAM_NUM(dev);
		IS_ISP_SET_PARAM_DMA_OUTPUT1_CMD(dev,
			DMA_OUTPUT_COMMAND_DISABLE);
		IS_ISP_SET_PARAM_DMA_OUTPUT1_WIDTH(dev, 0);
		IS_ISP_SET_PARAM_DMA_OUTPUT1_HEIGHT(dev, 0);
		IS_ISP_SET_PARAM_DMA_OUTPUT1_FORMAT(dev, 0);
		IS_ISP_SET_PARAM_DMA_OUTPUT1_BITWIDTH(dev, 0);
		IS_ISP_SET_PARAM_DMA_OUTPUT1_PLANE(dev, 0);
		IS_ISP_SET_PARAM_DMA_OUTPUT1_ORDER(dev, 0);
		IS_ISP_SET_PARAM_DMA_OUTPUT1_BUFFER_NUMBER(dev, 0);
		IS_ISP_SET_PARAM_DMA_OUTPUT1_BUFFER_ADDRESS(dev, 0);
		IS_ISP_SET_PARAM_DMA_OUTPUT1_ERR(dev,
			DMA_OUTPUT_ERROR_NO);
		IS_SET_PARAM_BIT(dev, PARAM_ISP_DMA1_OUTPUT);
		IS_INC_PARAM_NUM(dev);
		IS_ISP_SET_PARAM_DMA_OUTPUT2_CMD(dev,
			DMA_OUTPUT_COMMAND_DISABLE);
		IS_ISP_SET_PARAM_DMA_OUTPUT2_WIDTH(dev, 0);
		IS_ISP_SET_PARAM_DMA_OUTPUT2_HEIGHT(dev, 0);
		IS_ISP_SET_PARAM_DMA_OUTPUT2_FORMAT(dev, 0);
		IS_ISP_SET_PARAM_DMA_OUTPUT2_BITWIDTH(dev, 0);
		IS_ISP_SET_PARAM_DMA_OUTPUT2_PLANE(dev, 0);
		IS_ISP_SET_PARAM_DMA_OUTPUT2_ORDER(dev, 0);
		IS_ISP_SET_PARAM_DMA_OUTPUT2_BUFFER_NUMBER(dev, 0);
		IS_ISP_SET_PARAM_DMA_OUTPUT2_BUFFER_ADDRESS(dev, 0);
		IS_ISP_SET_PARAM_DMA_OUTPUT2_ERR(dev,
			DMA_OUTPUT_ERROR_NO);
		IS_SET_PARAM_BIT(dev, PARAM_ISP_DMA2_OUTPUT);
		IS_INC_PARAM_NUM(dev);

		/* DRC */
		IS_DRC_SET_PARAM_CONTROL_CMD(dev, CONTROL_COMMAND_START);
		IS_DRC_SET_PARAM_CONTROL_BYPASS(dev, CONTROL_BYPASS_ENABLE);
		IS_DRC_SET_PARAM_CONTROL_ERR(dev, CONTROL_ERROR_NO);
		IS_SET_PARAM_BIT(dev, PARAM_DRC_CONTROL);
		IS_INC_PARAM_NUM(dev);
		IS_DRC_SET_PARAM_OTF_INPUT_CMD(dev, OTF_INPUT_COMMAND_ENABLE);
		IS_DRC_SET_PARAM_OTF_INPUT_WIDTH(dev, 640);
		IS_DRC_SET_PARAM_OTF_INPUT_HEIGHT(dev, 480);
		IS_DRC_SET_PARAM_OTF_INPUT_FORMAT(dev,
			OTF_INPUT_FORMAT_YUV444);
		IS_DRC_SET_PARAM_OTF_INPUT_BITWIDTH(dev,
			OTF_INPUT_BIT_WIDTH_12BIT);
		IS_DRC_SET_PARAM_OTF_INPUT_ORDER(dev,
			OTF_INPUT_ORDER_BAYER_GR_BG);
		IS_DRC_SET_PARAM_OTF_INPUT_ERR(dev, OTF_INPUT_ERROR_NO);
		IS_SET_PARAM_BIT(dev, PARAM_DRC_OTF_INPUT);
		IS_INC_PARAM_NUM(dev);
		IS_DRC_SET_PARAM_DMA_INPUT_CMD(dev, DMA_INPUT_COMMAND_DISABLE);
		IS_DRC_SET_PARAM_DMA_INPUT_WIDTH(dev, 0);
		IS_DRC_SET_PARAM_DMA_INPUT_HEIGHT(dev, 0);
		IS_DRC_SET_PARAM_DMA_INPUT_FORMAT(dev, 0);
		IS_DRC_SET_PARAM_DMA_INPUT_BITWIDTH(dev, 0);
		IS_DRC_SET_PARAM_DMA_INPUT_PLANE(dev, 0);
		IS_DRC_SET_PARAM_DMA_INPUT_ORDER(dev, 0);
		IS_DRC_SET_PARAM_DMA_INPUT_BUFFERNUM(dev, 0);
		IS_DRC_SET_PARAM_DMA_INPUT_BUFFERADDR(dev, 0);
		IS_DRC_SET_PARAM_DMA_INPUT_ERR(dev, 0);
		IS_SET_PARAM_BIT(dev, PARAM_DRC_DMA_INPUT);
		IS_INC_PARAM_NUM(dev);
		IS_DRC_SET_PARAM_OTF_OUTPUT_CMD(dev,
			OTF_OUTPUT_COMMAND_ENABLE);
		IS_DRC_SET_PARAM_OTF_OUTPUT_WIDTH(dev, 640);
		IS_DRC_SET_PARAM_OTF_OUTPUT_HEIGHT(dev, 480);
		IS_DRC_SET_PARAM_OTF_OUTPUT_FORMAT(dev,
			OTF_OUTPUT_FORMAT_YUV444);
		IS_DRC_SET_PARAM_OTF_OUTPUT_BITWIDTH(dev,
			OTF_OUTPUT_BIT_WIDTH_8BIT);
		IS_DRC_SET_PARAM_OTF_OUTPUT_ORDER(dev,
			OTF_OUTPUT_ORDER_BAYER_GR_BG);
		IS_DRC_SET_PARAM_OTF_OUTPUT_ERR(dev, OTF_OUTPUT_ERROR_NO);
		IS_SET_PARAM_BIT(dev, PARAM_DRC_OTF_OUTPUT);
		IS_INC_PARAM_NUM(dev);

		/* FD */
		IS_FD_SET_PARAM_CONTROL_CMD(dev, CONTROL_COMMAND_STOP);
		IS_FD_SET_PARAM_CONTROL_BYPASS(dev, CONTROL_BYPASS_ENABLE);
		IS_FD_SET_PARAM_CONTROL_ERR(dev, CONTROL_ERROR_NO);
		IS_SET_PARAM_BIT(dev, PARAM_FD_CONTROL);
		IS_INC_PARAM_NUM(dev);
		IS_FD_SET_PARAM_OTF_INPUT_CMD(dev,
			OTF_INPUT_COMMAND_ENABLE);
		IS_FD_SET_PARAM_OTF_INPUT_WIDTH(dev, 640);
		IS_FD_SET_PARAM_OTF_INPUT_HEIGHT(dev, 480);
		IS_FD_SET_PARAM_OTF_INPUT_FORMAT(dev,
			OTF_INPUT_FORMAT_YUV444);
		IS_FD_SET_PARAM_OTF_INPUT_BITWIDTH(dev,
			OTF_INPUT_BIT_WIDTH_8BIT);
		IS_FD_SET_PARAM_OTF_INPUT_ORDER(dev,
			OTF_INPUT_ORDER_BAYER_GR_BG);
		IS_FD_SET_PARAM_OTF_INPUT_ERR(dev, OTF_INPUT_ERROR_NO);
		IS_SET_PARAM_BIT(dev, PARAM_FD_OTF_INPUT);
		IS_INC_PARAM_NUM(dev);
		IS_FD_SET_PARAM_DMA_INPUT_CMD(dev,
			DMA_INPUT_COMMAND_DISABLE);
		IS_FD_SET_PARAM_DMA_INPUT_WIDTH(dev, 0);
		IS_FD_SET_PARAM_DMA_INPUT_HEIGHT(dev, 0);
		IS_FD_SET_PARAM_DMA_INPUT_FORMAT(dev, 0);
		IS_FD_SET_PARAM_DMA_INPUT_BITWIDTH(dev, 0);
		IS_FD_SET_PARAM_DMA_INPUT_PLANE(dev, 0);
		IS_FD_SET_PARAM_DMA_INPUT_ORDER(dev, 0);
		IS_FD_SET_PARAM_DMA_INPUT_BUFFERNUM(dev, 0);
		IS_FD_SET_PARAM_DMA_INPUT_BUFFERADDR(dev, 0);
		IS_FD_SET_PARAM_DMA_INPUT_ERR(dev, 0);
		IS_SET_PARAM_BIT(dev, PARAM_FD_DMA_INPUT);
		IS_INC_PARAM_NUM(dev);
		IS_FD_SET_PARAM_FDCONTROL_MAX_NUMBER(dev, 10);
		IS_FD_SET_PARAM_FDCONTROL_ERR(dev, FD_ERROR_NO);
		IS_SET_PARAM_BIT(dev, PARAM_FD_FD);
		IS_INC_PARAM_NUM(dev);
		break;

	case ISS_CAPTURE_STILL:
		/* ISP */
		IS_ISP_SET_PARAM_CONTROL_CMD(dev, CONTROL_COMMAND_START);
		IS_ISP_SET_PARAM_CONTROL_BYPASS(dev, CONTROL_BYPASS_DISABLE);
		IS_ISP_SET_PARAM_CONTROL_ERR(dev, CONTROL_ERROR_NO);
		IS_SET_PARAM_BIT(dev, PARAM_ISP_CONTROL);
		IS_INC_PARAM_NUM(dev);
		IS_ISP_SET_PARAM_OTF_INPUT_CMD(dev, OTF_INPUT_COMMAND_ENABLE);
		IS_ISP_SET_PARAM_OTF_INPUT_WIDTH(dev, 640);
		IS_ISP_SET_PARAM_OTF_INPUT_HEIGHT(dev, 480);
#ifndef ISP_STRGEN
		IS_ISP_SET_PARAM_OTF_INPUT_FORMAT(dev, OTF_INPUT_FORMAT_BAYER);
#else
		IS_ISP_SET_PARAM_OTF_INPUT_FORMAT(dev,
			OTF_INPUT_FORMAT_STRGEN_COLORBAR_BAYER);
#endif
		IS_ISP_SET_PARAM_OTF_INPUT_BITWIDTH(dev,
			OTF_INPUT_BIT_WIDTH_10BIT);
		IS_ISP_SET_PARAM_OTF_INPUT_ORDER(dev,
			OTF_INPUT_ORDER_BAYER_GR_BG);
		IS_ISP_SET_PARAM_OTF_INPUT_ERR(dev, OTF_INPUT_ERROR_NO);
		IS_SET_PARAM_BIT(dev, PARAM_ISP_OTF_INPUT);
		IS_INC_PARAM_NUM(dev);
		IS_ISP_SET_PARAM_DMA_INPUT1_CMD(dev,
			DMA_INPUT_COMMAND_DISABLE);
		IS_ISP_SET_PARAM_DMA_INPUT1_WIDTH(dev, 0);
		IS_ISP_SET_PARAM_DMA_INPUT1_HEIGHT(dev, 0);
		IS_ISP_SET_PARAM_DMA_INPUT1_FORMAT(dev, 0);
		IS_ISP_SET_PARAM_DMA_INPUT1_BITWIDTH(dev, 0);
		IS_ISP_SET_PARAM_DMA_INPUT1_PLANE(dev, 0);
		IS_ISP_SET_PARAM_DMA_INPUT1_ORDER(dev, 0);
		IS_ISP_SET_PARAM_DMA_INPUT1_BUFFERNUM(dev, 0);
		IS_ISP_SET_PARAM_DMA_INPUT1_BUFFERADDR(dev, 0);
		IS_ISP_SET_PARAM_DMA_INPUT1_ERR(dev, 0);
		IS_SET_PARAM_BIT(dev, PARAM_ISP_DMA1_INPUT);
		IS_INC_PARAM_NUM(dev);
		IS_ISP_SET_PARAM_DMA_INPUT2_CMD(dev,
			DMA_INPUT_COMMAND_DISABLE);
		IS_ISP_SET_PARAM_DMA_INPUT2_WIDTH(dev, 0);
		IS_ISP_SET_PARAM_DMA_INPUT2_HEIGHT(dev, 0);
		IS_ISP_SET_PARAM_DMA_INPUT2_FORMAT(dev, 0);
		IS_ISP_SET_PARAM_DMA_INPUT2_BITWIDTH(dev, 0);
		IS_ISP_SET_PARAM_DMA_INPUT2_PLANE(dev, 0);
		IS_ISP_SET_PARAM_DMA_INPUT2_ORDER(dev, 0);
		IS_ISP_SET_PARAM_DMA_INPUT2_BUFFERNUM(dev, 0);
		IS_ISP_SET_PARAM_DMA_INPUT2_BUFFERADDR(dev, 0);
		IS_ISP_SET_PARAM_DMA_INPUT2_ERR(dev, 0);
		IS_SET_PARAM_BIT(dev, PARAM_ISP_DMA2_INPUT);
		IS_INC_PARAM_NUM(dev);
		IS_ISP_SET_PARAM_AF_CMD(dev, ISP_AF_COMMAND_SET_FOCUSMODE);
		IS_ISP_SET_PARAM_AF_MODE(dev, ISP_AF_MODE_AUTO);
		IS_ISP_SET_PARAM_AF_FACE(dev, ISP_AF_FACE_DISABLE);
		IS_ISP_SET_PARAM_AF_CONTINUOUS(dev, ISP_AF_CONTINUOUS_DISABLE);
		IS_ISP_SET_PARAM_AF_WIN_POS_X(dev, 0);
		IS_ISP_SET_PARAM_AF_WIN_POS_Y(dev, 0);
		IS_ISP_SET_PARAM_AF_WIN_WIDTH(dev, 0);
		IS_ISP_SET_PARAM_AF_WIN_HEIGHT(dev, 0);
		IS_ISP_SET_PARAM_AF_ERR(dev, ISP_AF_ERROR_NO);
		IS_SET_PARAM_BIT(dev, PARAM_ISP_AF);
		IS_INC_PARAM_NUM(dev);
		IS_ISP_SET_PARAM_FLASH_CMD(dev,
			ISP_FLASH_COMMAND_DISABLE);
		IS_ISP_SET_PARAM_FLASH_REDEYE(dev,
			ISP_FLASH_REDEYE_DISABLE);
		IS_ISP_SET_PARAM_FLASH_ERR(dev, ISP_FLASH_ERROR_NO);
		IS_SET_PARAM_BIT(dev, PARAM_ISP_FLASH);
		IS_INC_PARAM_NUM(dev);
		IS_ISP_SET_PARAM_AWB_CMD(dev, ISP_AWB_COMMAND_AUTO);
		IS_ISP_SET_PARAM_AWB_ILLUMINATION(dev, 0);
		IS_ISP_SET_PARAM_AWB_ERR(dev, ISP_AWB_ERROR_NO);
		IS_SET_PARAM_BIT(dev, PARAM_ISP_AWB);
		IS_INC_PARAM_NUM(dev);
		IS_ISP_SET_PARAM_EFFECT_CMD(dev, ISP_IMAGE_EFFECT_DISABLE);
		IS_ISP_SET_PARAM_EFFECT_ERR(dev, ISP_IMAGE_EFFECT_ERROR_NO);
		IS_SET_PARAM_BIT(dev, PARAM_ISP_IMAGE_EFFECT);
		IS_INC_PARAM_NUM(dev);
		IS_ISP_SET_PARAM_ISO_CMD(dev, ISP_ISO_COMMAND_AUTO);
		IS_ISP_SET_PARAM_ISO_VALUE(dev, 0);
		IS_ISP_SET_PARAM_ISO_ERR(dev, ISP_ISO_ERROR_NO);
		IS_SET_PARAM_BIT(dev, PARAM_ISP_ISO);
		IS_INC_PARAM_NUM(dev);
		IS_ISP_SET_PARAM_ADJUST_CMD(dev,
			ISP_ADJUST_COMMAND_AUTOCONTRAST);
		IS_ISP_SET_PARAM_ADJUST_CONTRAST(dev, 0);
		IS_ISP_SET_PARAM_ADJUST_SATURATION(dev, 0);
		IS_ISP_SET_PARAM_ADJUST_SHARPNESS(dev, 0);
		IS_ISP_SET_PARAM_ADJUST_EXPOSURE(dev, 0);
		IS_ISP_SET_PARAM_ADJUST_BRIGHTNESS(dev, 0);
		IS_ISP_SET_PARAM_ADJUST_HUE(dev, 0);
		IS_ISP_SET_PARAM_ADJUST_ERR(dev, ISP_ADJUST_ERROR_NO);
		IS_SET_PARAM_BIT(dev, PARAM_ISP_ADJUST);
		IS_INC_PARAM_NUM(dev);
		IS_ISP_SET_PARAM_METERING_CMD(dev,
			ISP_METERING_COMMAND_MATRIX);
		IS_ISP_SET_PARAM_METERING_WIN_POS_X(dev, 0);
		IS_ISP_SET_PARAM_METERING_WIN_POS_Y(dev, 0);
		IS_ISP_SET_PARAM_METERING_WIN_WIDTH(dev, 640);
		IS_ISP_SET_PARAM_METERING_WIN_HEIGHT(dev, 480);
		IS_ISP_SET_PARAM_METERING_ERR(dev,
			ISP_METERING_ERROR_NO);
		IS_SET_PARAM_BIT(dev, PARAM_ISP_METERING);
		IS_INC_PARAM_NUM(dev);
		IS_ISP_SET_PARAM_AFC_CMD(dev, ISP_AFC_COMMAND_AUTO);
		IS_ISP_SET_PARAM_AFC_MANUAL(dev, 0);
		IS_ISP_SET_PARAM_AFC_ERR(dev, ISP_AFC_ERROR_NO);
		IS_SET_PARAM_BIT(dev, PARAM_ISP_AFC);
		IS_INC_PARAM_NUM(dev);
		IS_ISP_SET_PARAM_OTF_OUTPUT_CMD(dev,
			OTF_OUTPUT_COMMAND_ENABLE);
		IS_ISP_SET_PARAM_OTF_OUTPUT_WIDTH(dev, 640);
		IS_ISP_SET_PARAM_OTF_OUTPUT_HEIGHT(dev, 480);
		IS_ISP_SET_PARAM_OTF_OUTPUT_FORMAT(dev,
			OTF_OUTPUT_FORMAT_YUV444);
		IS_ISP_SET_PARAM_OTF_OUTPUT_BITWIDTH(dev,
			OTF_OUTPUT_BIT_WIDTH_12BIT);
		IS_ISP_SET_PARAM_OTF_OUTPUT_ORDER(dev,
			OTF_OUTPUT_ORDER_BAYER_GR_BG);
		IS_ISP_SET_PARAM_OTF_OUTPUT_ERR(dev,
			OTF_OUTPUT_ERROR_NO);
		IS_SET_PARAM_BIT(dev, PARAM_ISP_OTF_OUTPUT);
		IS_INC_PARAM_NUM(dev);
		IS_ISP_SET_PARAM_DMA_OUTPUT1_CMD(dev,
			DMA_OUTPUT_COMMAND_DISABLE);
		IS_ISP_SET_PARAM_DMA_OUTPUT1_WIDTH(dev, 0);
		IS_ISP_SET_PARAM_DMA_OUTPUT1_HEIGHT(dev, 0);
		IS_ISP_SET_PARAM_DMA_OUTPUT1_FORMAT(dev, 0);
		IS_ISP_SET_PARAM_DMA_OUTPUT1_BITWIDTH(dev, 0);
		IS_ISP_SET_PARAM_DMA_OUTPUT1_PLANE(dev, 0);
		IS_ISP_SET_PARAM_DMA_OUTPUT1_ORDER(dev, 0);
		IS_ISP_SET_PARAM_DMA_OUTPUT1_BUFFER_NUMBER(dev, 0);
		IS_ISP_SET_PARAM_DMA_OUTPUT1_BUFFER_ADDRESS(dev, 0);
		IS_ISP_SET_PARAM_DMA_OUTPUT1_ERR(dev,
			DMA_OUTPUT_ERROR_NO);
		IS_SET_PARAM_BIT(dev, PARAM_ISP_DMA1_OUTPUT);
		IS_INC_PARAM_NUM(dev);
		IS_ISP_SET_PARAM_DMA_OUTPUT2_CMD(dev,
			DMA_OUTPUT_COMMAND_DISABLE);
		IS_ISP_SET_PARAM_DMA_OUTPUT2_WIDTH(dev, 0);
		IS_ISP_SET_PARAM_DMA_OUTPUT2_HEIGHT(dev, 0);
		IS_ISP_SET_PARAM_DMA_OUTPUT2_FORMAT(dev, 0);
		IS_ISP_SET_PARAM_DMA_OUTPUT2_BITWIDTH(dev, 0);
		IS_ISP_SET_PARAM_DMA_OUTPUT2_PLANE(dev, 0);
		IS_ISP_SET_PARAM_DMA_OUTPUT2_ORDER(dev, 0);
		IS_ISP_SET_PARAM_DMA_OUTPUT2_BUFFER_NUMBER(dev, 0);
		IS_ISP_SET_PARAM_DMA_OUTPUT2_BUFFER_ADDRESS(dev, 0);
		IS_ISP_SET_PARAM_DMA_OUTPUT2_ERR(dev,
			DMA_OUTPUT_ERROR_NO);
		IS_SET_PARAM_BIT(dev, PARAM_ISP_DMA2_OUTPUT);
		IS_INC_PARAM_NUM(dev);

		/* DRC */
		IS_DRC_SET_PARAM_CONTROL_CMD(dev, CONTROL_COMMAND_START);
		IS_DRC_SET_PARAM_CONTROL_BYPASS(dev, CONTROL_BYPASS_ENABLE);
		IS_DRC_SET_PARAM_CONTROL_ERR(dev, CONTROL_ERROR_NO);
		IS_SET_PARAM_BIT(dev, PARAM_DRC_CONTROL);
		IS_INC_PARAM_NUM(dev);
		IS_DRC_SET_PARAM_OTF_INPUT_CMD(dev, OTF_INPUT_COMMAND_ENABLE);
		IS_DRC_SET_PARAM_OTF_INPUT_WIDTH(dev, 640);
		IS_DRC_SET_PARAM_OTF_INPUT_HEIGHT(dev, 480);
		IS_DRC_SET_PARAM_OTF_INPUT_FORMAT(dev,
			OTF_INPUT_FORMAT_YUV444);
		IS_DRC_SET_PARAM_OTF_INPUT_BITWIDTH(dev,
			OTF_INPUT_BIT_WIDTH_12BIT);
		IS_DRC_SET_PARAM_OTF_INPUT_ORDER(dev,
			OTF_INPUT_ORDER_BAYER_GR_BG);
		IS_DRC_SET_PARAM_OTF_INPUT_ERR(dev, OTF_INPUT_ERROR_NO);
		IS_SET_PARAM_BIT(dev, PARAM_DRC_OTF_INPUT);
		IS_INC_PARAM_NUM(dev);
		IS_DRC_SET_PARAM_DMA_INPUT_CMD(dev, DMA_INPUT_COMMAND_DISABLE);
		IS_DRC_SET_PARAM_DMA_INPUT_WIDTH(dev, 0);
		IS_DRC_SET_PARAM_DMA_INPUT_HEIGHT(dev, 0);
		IS_DRC_SET_PARAM_DMA_INPUT_FORMAT(dev, 0);
		IS_DRC_SET_PARAM_DMA_INPUT_BITWIDTH(dev, 0);
		IS_DRC_SET_PARAM_DMA_INPUT_PLANE(dev, 0);
		IS_DRC_SET_PARAM_DMA_INPUT_ORDER(dev, 0);
		IS_DRC_SET_PARAM_DMA_INPUT_BUFFERNUM(dev, 0);
		IS_DRC_SET_PARAM_DMA_INPUT_BUFFERADDR(dev, 0);
		IS_DRC_SET_PARAM_DMA_INPUT_ERR(dev, 0);
		IS_SET_PARAM_BIT(dev, PARAM_DRC_DMA_INPUT);
		IS_INC_PARAM_NUM(dev);
		IS_DRC_SET_PARAM_OTF_OUTPUT_CMD(dev,
			OTF_OUTPUT_COMMAND_ENABLE);
		IS_DRC_SET_PARAM_OTF_OUTPUT_WIDTH(dev, 640);
		IS_DRC_SET_PARAM_OTF_OUTPUT_HEIGHT(dev, 480);
		IS_DRC_SET_PARAM_OTF_OUTPUT_FORMAT(dev,
			OTF_OUTPUT_FORMAT_YUV444);
		IS_DRC_SET_PARAM_OTF_OUTPUT_BITWIDTH(dev,
			OTF_OUTPUT_BIT_WIDTH_8BIT);
		IS_DRC_SET_PARAM_OTF_OUTPUT_ORDER(dev,
			OTF_OUTPUT_ORDER_BAYER_GR_BG);
		IS_DRC_SET_PARAM_OTF_OUTPUT_ERR(dev, OTF_OUTPUT_ERROR_NO);
		IS_SET_PARAM_BIT(dev, PARAM_DRC_OTF_OUTPUT);
		IS_INC_PARAM_NUM(dev);

		/* FD */
		IS_FD_SET_PARAM_CONTROL_CMD(dev, CONTROL_COMMAND_STOP);
		IS_FD_SET_PARAM_CONTROL_BYPASS(dev, CONTROL_BYPASS_ENABLE);
		IS_FD_SET_PARAM_CONTROL_ERR(dev, CONTROL_ERROR_NO);
		IS_SET_PARAM_BIT(dev, PARAM_FD_CONTROL);
		IS_INC_PARAM_NUM(dev);
		IS_FD_SET_PARAM_OTF_INPUT_CMD(dev,
			OTF_INPUT_COMMAND_ENABLE);
		IS_FD_SET_PARAM_OTF_INPUT_WIDTH(dev, 640);
		IS_FD_SET_PARAM_OTF_INPUT_HEIGHT(dev, 480);
		IS_FD_SET_PARAM_OTF_INPUT_FORMAT(dev,
			OTF_INPUT_FORMAT_YUV444);
		IS_FD_SET_PARAM_OTF_INPUT_BITWIDTH(dev,
			OTF_INPUT_BIT_WIDTH_8BIT);
		IS_FD_SET_PARAM_OTF_INPUT_ORDER(dev,
			OTF_INPUT_ORDER_BAYER_GR_BG);
		IS_FD_SET_PARAM_OTF_INPUT_ERR(dev, OTF_INPUT_ERROR_NO);
		IS_SET_PARAM_BIT(dev, PARAM_FD_OTF_INPUT);
		IS_INC_PARAM_NUM(dev);
		IS_FD_SET_PARAM_DMA_INPUT_CMD(dev,
			DMA_INPUT_COMMAND_DISABLE);
		IS_FD_SET_PARAM_DMA_INPUT_WIDTH(dev, 0);
		IS_FD_SET_PARAM_DMA_INPUT_HEIGHT(dev, 0);
		IS_FD_SET_PARAM_DMA_INPUT_FORMAT(dev, 0);
		IS_FD_SET_PARAM_DMA_INPUT_BITWIDTH(dev, 0);
		IS_FD_SET_PARAM_DMA_INPUT_PLANE(dev, 0);
		IS_FD_SET_PARAM_DMA_INPUT_ORDER(dev, 0);
		IS_FD_SET_PARAM_DMA_INPUT_BUFFERNUM(dev, 0);
		IS_FD_SET_PARAM_DMA_INPUT_BUFFERADDR(dev, 0);
		IS_FD_SET_PARAM_DMA_INPUT_ERR(dev, 0);
		IS_SET_PARAM_BIT(dev, PARAM_FD_DMA_INPUT);
		IS_INC_PARAM_NUM(dev);
		IS_FD_SET_PARAM_FDCONTROL_MAX_NUMBER(dev, 10);
		IS_FD_SET_PARAM_FDCONTROL_ERR(dev, FD_ERROR_NO);
		IS_SET_PARAM_BIT(dev, PARAM_FD_FD);
		IS_INC_PARAM_NUM(dev);
		break;

	case ISS_CAPTURE_VIDEO:
		/* ISP */
		IS_ISP_SET_PARAM_CONTROL_CMD(dev, CONTROL_COMMAND_START);
		IS_ISP_SET_PARAM_CONTROL_BYPASS(dev, CONTROL_BYPASS_DISABLE);
		IS_ISP_SET_PARAM_CONTROL_ERR(dev, CONTROL_ERROR_NO);
		IS_SET_PARAM_BIT(dev, PARAM_ISP_CONTROL);
		IS_INC_PARAM_NUM(dev);
		IS_ISP_SET_PARAM_OTF_INPUT_CMD(dev, OTF_INPUT_COMMAND_ENABLE);
		IS_ISP_SET_PARAM_OTF_INPUT_WIDTH(dev, 1920);
		IS_ISP_SET_PARAM_OTF_INPUT_HEIGHT(dev, 1080);
#ifndef ISP_STRGEN
		IS_ISP_SET_PARAM_OTF_INPUT_FORMAT(dev, OTF_INPUT_FORMAT_BAYER);
#else
		IS_ISP_SET_PARAM_OTF_INPUT_FORMAT(dev,
			OTF_INPUT_FORMAT_STRGEN_COLORBAR_BAYER);
#endif
		IS_ISP_SET_PARAM_OTF_INPUT_BITWIDTH(dev,
			OTF_INPUT_BIT_WIDTH_10BIT);
		IS_ISP_SET_PARAM_OTF_INPUT_ORDER(dev,
			OTF_INPUT_ORDER_BAYER_GR_BG);
		IS_ISP_SET_PARAM_OTF_INPUT_ERR(dev, OTF_INPUT_ERROR_NO);
		IS_SET_PARAM_BIT(dev, PARAM_ISP_OTF_INPUT);
		IS_INC_PARAM_NUM(dev);
		IS_ISP_SET_PARAM_DMA_INPUT1_CMD(dev,
			DMA_INPUT_COMMAND_DISABLE);
		IS_ISP_SET_PARAM_DMA_INPUT1_WIDTH(dev, 0);
		IS_ISP_SET_PARAM_DMA_INPUT1_HEIGHT(dev, 0);
		IS_ISP_SET_PARAM_DMA_INPUT1_FORMAT(dev, 0);
		IS_ISP_SET_PARAM_DMA_INPUT1_BITWIDTH(dev, 0);
		IS_ISP_SET_PARAM_DMA_INPUT1_PLANE(dev, 0);
		IS_ISP_SET_PARAM_DMA_INPUT1_ORDER(dev, 0);
		IS_ISP_SET_PARAM_DMA_INPUT1_BUFFERNUM(dev, 0);
		IS_ISP_SET_PARAM_DMA_INPUT1_BUFFERADDR(dev, 0);
		IS_ISP_SET_PARAM_DMA_INPUT1_ERR(dev, 0);
		IS_SET_PARAM_BIT(dev, PARAM_ISP_DMA1_INPUT);
		IS_INC_PARAM_NUM(dev);
		IS_ISP_SET_PARAM_DMA_INPUT2_CMD(dev,
			DMA_INPUT_COMMAND_DISABLE);
		IS_ISP_SET_PARAM_DMA_INPUT2_WIDTH(dev, 0);
		IS_ISP_SET_PARAM_DMA_INPUT2_HEIGHT(dev, 0);
		IS_ISP_SET_PARAM_DMA_INPUT2_FORMAT(dev, 0);
		IS_ISP_SET_PARAM_DMA_INPUT2_BITWIDTH(dev, 0);
		IS_ISP_SET_PARAM_DMA_INPUT2_PLANE(dev, 0);
		IS_ISP_SET_PARAM_DMA_INPUT2_ORDER(dev, 0);
		IS_ISP_SET_PARAM_DMA_INPUT2_BUFFERNUM(dev, 0);
		IS_ISP_SET_PARAM_DMA_INPUT2_BUFFERADDR(dev, 0);
		IS_ISP_SET_PARAM_DMA_INPUT2_ERR(dev, 0);
		IS_SET_PARAM_BIT(dev, PARAM_ISP_DMA2_INPUT);
		IS_INC_PARAM_NUM(dev);
		IS_ISP_SET_PARAM_AF_CMD(dev, ISP_AF_COMMAND_SET_FOCUSMODE);
		IS_ISP_SET_PARAM_AF_MODE(dev, ISP_AF_MODE_AUTO);
		IS_ISP_SET_PARAM_AF_FACE(dev, ISP_AF_FACE_DISABLE);
		IS_ISP_SET_PARAM_AF_CONTINUOUS(dev, ISP_AF_CONTINUOUS_DISABLE);
		IS_ISP_SET_PARAM_AF_WIN_POS_X(dev, 0);
		IS_ISP_SET_PARAM_AF_WIN_POS_Y(dev, 0);
		IS_ISP_SET_PARAM_AF_WIN_WIDTH(dev, 0);
		IS_ISP_SET_PARAM_AF_WIN_HEIGHT(dev, 0);
		IS_ISP_SET_PARAM_AF_ERR(dev, ISP_AF_ERROR_NO);
		IS_SET_PARAM_BIT(dev, PARAM_ISP_AF);
		IS_INC_PARAM_NUM(dev);
		IS_ISP_SET_PARAM_FLASH_CMD(dev,
			ISP_FLASH_COMMAND_DISABLE);
		IS_ISP_SET_PARAM_FLASH_REDEYE(dev,
			ISP_FLASH_REDEYE_DISABLE);
		IS_ISP_SET_PARAM_FLASH_ERR(dev, ISP_FLASH_ERROR_NO);
		IS_SET_PARAM_BIT(dev, PARAM_ISP_FLASH);
		IS_INC_PARAM_NUM(dev);
		IS_ISP_SET_PARAM_AWB_CMD(dev, ISP_AWB_COMMAND_AUTO);
		IS_ISP_SET_PARAM_AWB_ILLUMINATION(dev, 0);
		IS_ISP_SET_PARAM_AWB_ERR(dev, ISP_AWB_ERROR_NO);
		IS_SET_PARAM_BIT(dev, PARAM_ISP_AWB);
		IS_INC_PARAM_NUM(dev);
		IS_ISP_SET_PARAM_EFFECT_CMD(dev, ISP_IMAGE_EFFECT_DISABLE);
		IS_ISP_SET_PARAM_EFFECT_ERR(dev, ISP_IMAGE_EFFECT_ERROR_NO);
		IS_SET_PARAM_BIT(dev, PARAM_ISP_IMAGE_EFFECT);
		IS_INC_PARAM_NUM(dev);
		IS_ISP_SET_PARAM_ISO_CMD(dev, ISP_ISO_COMMAND_AUTO);
		IS_ISP_SET_PARAM_ISO_VALUE(dev, 0);
		IS_ISP_SET_PARAM_ISO_ERR(dev, ISP_ISO_ERROR_NO);
		IS_SET_PARAM_BIT(dev, PARAM_ISP_ISO);
		IS_INC_PARAM_NUM(dev);
		IS_ISP_SET_PARAM_ADJUST_CMD(dev,
			ISP_ADJUST_COMMAND_AUTOCONTRAST);
		IS_ISP_SET_PARAM_ADJUST_CONTRAST(dev, 0);
		IS_ISP_SET_PARAM_ADJUST_SATURATION(dev, 0);
		IS_ISP_SET_PARAM_ADJUST_SHARPNESS(dev, 0);
		IS_ISP_SET_PARAM_ADJUST_EXPOSURE(dev, 0);
		IS_ISP_SET_PARAM_ADJUST_BRIGHTNESS(dev, 0);
		IS_ISP_SET_PARAM_ADJUST_HUE(dev, 0);
		IS_ISP_SET_PARAM_ADJUST_ERR(dev, ISP_ADJUST_ERROR_NO);
		IS_SET_PARAM_BIT(dev, PARAM_ISP_ADJUST);
		IS_INC_PARAM_NUM(dev);
		IS_ISP_SET_PARAM_METERING_CMD(dev,
			ISP_METERING_COMMAND_MATRIX);
		IS_ISP_SET_PARAM_METERING_WIN_POS_X(dev, 0);
		IS_ISP_SET_PARAM_METERING_WIN_POS_Y(dev, 0);
		IS_ISP_SET_PARAM_METERING_WIN_WIDTH(dev, 1920);
		IS_ISP_SET_PARAM_METERING_WIN_HEIGHT(dev, 1080);
		IS_ISP_SET_PARAM_METERING_ERR(dev,
			ISP_METERING_ERROR_NO);
		IS_SET_PARAM_BIT(dev, PARAM_ISP_METERING);
		IS_INC_PARAM_NUM(dev);
		IS_ISP_SET_PARAM_AFC_CMD(dev, ISP_AFC_COMMAND_AUTO);
		IS_ISP_SET_PARAM_AFC_MANUAL(dev, 0);
		IS_ISP_SET_PARAM_AFC_ERR(dev, ISP_AFC_ERROR_NO);
		IS_SET_PARAM_BIT(dev, PARAM_ISP_AFC);
		IS_INC_PARAM_NUM(dev);
		IS_ISP_SET_PARAM_OTF_OUTPUT_CMD(dev,
			OTF_OUTPUT_COMMAND_ENABLE);
		IS_ISP_SET_PARAM_OTF_OUTPUT_WIDTH(dev, 1920);
		IS_ISP_SET_PARAM_OTF_OUTPUT_HEIGHT(dev, 1080);
		IS_ISP_SET_PARAM_OTF_OUTPUT_FORMAT(dev,
			OTF_OUTPUT_FORMAT_YUV444);
		IS_ISP_SET_PARAM_OTF_OUTPUT_BITWIDTH(dev,
			OTF_OUTPUT_BIT_WIDTH_12BIT);
		IS_ISP_SET_PARAM_OTF_OUTPUT_ORDER(dev,
			OTF_OUTPUT_ORDER_BAYER_GR_BG);
		IS_ISP_SET_PARAM_OTF_OUTPUT_ERR(dev,
			OTF_OUTPUT_ERROR_NO);
		IS_SET_PARAM_BIT(dev, PARAM_ISP_OTF_OUTPUT);
		IS_INC_PARAM_NUM(dev);
		IS_ISP_SET_PARAM_DMA_OUTPUT1_CMD(dev,
			DMA_OUTPUT_COMMAND_DISABLE);
		IS_ISP_SET_PARAM_DMA_OUTPUT1_WIDTH(dev, 0);
		IS_ISP_SET_PARAM_DMA_OUTPUT1_HEIGHT(dev, 0);
		IS_ISP_SET_PARAM_DMA_OUTPUT1_FORMAT(dev, 0);
		IS_ISP_SET_PARAM_DMA_OUTPUT1_BITWIDTH(dev, 0);
		IS_ISP_SET_PARAM_DMA_OUTPUT1_PLANE(dev, 0);
		IS_ISP_SET_PARAM_DMA_OUTPUT1_ORDER(dev, 0);
		IS_ISP_SET_PARAM_DMA_OUTPUT1_BUFFER_NUMBER(dev, 0);
		IS_ISP_SET_PARAM_DMA_OUTPUT1_BUFFER_ADDRESS(dev, 0);
		IS_ISP_SET_PARAM_DMA_OUTPUT1_ERR(dev,
			DMA_OUTPUT_ERROR_NO);
		IS_SET_PARAM_BIT(dev, PARAM_ISP_DMA1_OUTPUT);
		IS_INC_PARAM_NUM(dev);
		IS_ISP_SET_PARAM_DMA_OUTPUT2_CMD(dev,
			DMA_OUTPUT_COMMAND_DISABLE);
		IS_ISP_SET_PARAM_DMA_OUTPUT2_WIDTH(dev, 0);
		IS_ISP_SET_PARAM_DMA_OUTPUT2_HEIGHT(dev, 0);
		IS_ISP_SET_PARAM_DMA_OUTPUT2_FORMAT(dev, 0);
		IS_ISP_SET_PARAM_DMA_OUTPUT2_BITWIDTH(dev, 0);
		IS_ISP_SET_PARAM_DMA_OUTPUT2_PLANE(dev, 0);
		IS_ISP_SET_PARAM_DMA_OUTPUT2_ORDER(dev, 0);
		IS_ISP_SET_PARAM_DMA_OUTPUT2_BUFFER_NUMBER(dev, 0);
		IS_ISP_SET_PARAM_DMA_OUTPUT2_BUFFER_ADDRESS(dev, 0);
		IS_ISP_SET_PARAM_DMA_OUTPUT2_ERR(dev,
			DMA_OUTPUT_ERROR_NO);
		IS_SET_PARAM_BIT(dev, PARAM_ISP_DMA2_OUTPUT);
		IS_INC_PARAM_NUM(dev);

		/* DRC */
		IS_DRC_SET_PARAM_CONTROL_CMD(dev, CONTROL_COMMAND_START);
		IS_DRC_SET_PARAM_CONTROL_BYPASS(dev, CONTROL_BYPASS_ENABLE);
		IS_DRC_SET_PARAM_CONTROL_ERR(dev, CONTROL_ERROR_NO);
		IS_SET_PARAM_BIT(dev, PARAM_DRC_CONTROL);
		IS_INC_PARAM_NUM(dev);
		IS_DRC_SET_PARAM_OTF_INPUT_CMD(dev, OTF_INPUT_COMMAND_ENABLE);
		IS_DRC_SET_PARAM_OTF_INPUT_WIDTH(dev, 1920);
		IS_DRC_SET_PARAM_OTF_INPUT_HEIGHT(dev, 1080);
		IS_DRC_SET_PARAM_OTF_INPUT_FORMAT(dev,
			OTF_INPUT_FORMAT_YUV444);
		IS_DRC_SET_PARAM_OTF_INPUT_BITWIDTH(dev,
			OTF_INPUT_BIT_WIDTH_12BIT);
		IS_DRC_SET_PARAM_OTF_INPUT_ORDER(dev,
			OTF_INPUT_ORDER_BAYER_GR_BG);
		IS_DRC_SET_PARAM_OTF_INPUT_ERR(dev, OTF_INPUT_ERROR_NO);
		IS_SET_PARAM_BIT(dev, PARAM_DRC_OTF_INPUT);
		IS_INC_PARAM_NUM(dev);
		IS_DRC_SET_PARAM_DMA_INPUT_CMD(dev, DMA_INPUT_COMMAND_DISABLE);
		IS_DRC_SET_PARAM_DMA_INPUT_WIDTH(dev, 0);
		IS_DRC_SET_PARAM_DMA_INPUT_HEIGHT(dev, 0);
		IS_DRC_SET_PARAM_DMA_INPUT_FORMAT(dev, 0);
		IS_DRC_SET_PARAM_DMA_INPUT_BITWIDTH(dev, 0);
		IS_DRC_SET_PARAM_DMA_INPUT_PLANE(dev, 0);
		IS_DRC_SET_PARAM_DMA_INPUT_ORDER(dev, 0);
		IS_DRC_SET_PARAM_DMA_INPUT_BUFFERNUM(dev, 0);
		IS_DRC_SET_PARAM_DMA_INPUT_BUFFERADDR(dev, 0);
		IS_DRC_SET_PARAM_DMA_INPUT_ERR(dev, 0);
		IS_SET_PARAM_BIT(dev, PARAM_DRC_DMA_INPUT);
		IS_INC_PARAM_NUM(dev);
		IS_DRC_SET_PARAM_OTF_OUTPUT_CMD(dev,
			OTF_OUTPUT_COMMAND_ENABLE);
		IS_DRC_SET_PARAM_OTF_OUTPUT_WIDTH(dev, 1920);
		IS_DRC_SET_PARAM_OTF_OUTPUT_HEIGHT(dev, 1080);
		IS_DRC_SET_PARAM_OTF_OUTPUT_FORMAT(dev,
			OTF_OUTPUT_FORMAT_YUV444);
		IS_DRC_SET_PARAM_OTF_OUTPUT_BITWIDTH(dev,
			OTF_OUTPUT_BIT_WIDTH_8BIT);
		IS_DRC_SET_PARAM_OTF_OUTPUT_ORDER(dev,
			OTF_OUTPUT_ORDER_BAYER_GR_BG);
		IS_DRC_SET_PARAM_OTF_OUTPUT_ERR(dev, OTF_OUTPUT_ERROR_NO);
		IS_SET_PARAM_BIT(dev, PARAM_DRC_OTF_OUTPUT);
		IS_INC_PARAM_NUM(dev);

		/* FD */
		IS_FD_SET_PARAM_CONTROL_CMD(dev, CONTROL_COMMAND_STOP);
		IS_FD_SET_PARAM_CONTROL_BYPASS(dev, CONTROL_BYPASS_ENABLE);
		IS_FD_SET_PARAM_CONTROL_ERR(dev, CONTROL_ERROR_NO);
		IS_SET_PARAM_BIT(dev, PARAM_FD_CONTROL);
		IS_INC_PARAM_NUM(dev);
		IS_FD_SET_PARAM_OTF_INPUT_CMD(dev,
			OTF_INPUT_COMMAND_ENABLE);
		IS_FD_SET_PARAM_OTF_INPUT_WIDTH(dev, 1920);
		IS_FD_SET_PARAM_OTF_INPUT_HEIGHT(dev, 1080);
		IS_FD_SET_PARAM_OTF_INPUT_FORMAT(dev,
			OTF_INPUT_FORMAT_YUV444);
		IS_FD_SET_PARAM_OTF_INPUT_BITWIDTH(dev,
			OTF_INPUT_BIT_WIDTH_8BIT);
		IS_FD_SET_PARAM_OTF_INPUT_ORDER(dev,
			OTF_INPUT_ORDER_BAYER_GR_BG);
		IS_FD_SET_PARAM_OTF_INPUT_ERR(dev, OTF_INPUT_ERROR_NO);
		IS_SET_PARAM_BIT(dev, PARAM_FD_OTF_INPUT);
		IS_INC_PARAM_NUM(dev);
		IS_FD_SET_PARAM_DMA_INPUT_CMD(dev,
			DMA_INPUT_COMMAND_DISABLE);
		IS_FD_SET_PARAM_DMA_INPUT_WIDTH(dev, 0);
		IS_FD_SET_PARAM_DMA_INPUT_HEIGHT(dev, 0);
		IS_FD_SET_PARAM_DMA_INPUT_FORMAT(dev, 0);
		IS_FD_SET_PARAM_DMA_INPUT_BITWIDTH(dev, 0);
		IS_FD_SET_PARAM_DMA_INPUT_PLANE(dev, 0);
		IS_FD_SET_PARAM_DMA_INPUT_ORDER(dev, 0);
		IS_FD_SET_PARAM_DMA_INPUT_BUFFERNUM(dev, 0);
		IS_FD_SET_PARAM_DMA_INPUT_BUFFERADDR(dev, 0);
		IS_FD_SET_PARAM_DMA_INPUT_ERR(dev, 0);
		IS_SET_PARAM_BIT(dev, PARAM_FD_DMA_INPUT);
		IS_INC_PARAM_NUM(dev);
		IS_FD_SET_PARAM_FDCONTROL_MAX_NUMBER(dev, 10);
		IS_FD_SET_PARAM_FDCONTROL_ERR(dev, FD_ERROR_NO);
		IS_SET_PARAM_BIT(dev, PARAM_FD_FD);
		IS_INC_PARAM_NUM(dev);
		break;
	}
}
