obj-$(CONFIG_EXYNOS_MEDIA_DEVICE)	+= mdev/
obj-$(CONFIG_VIDEO_EXYNOS_GSCALER)	+= gsc/
obj-$(CONFIG_VIDEO_EXYNOS)		+= fimc-lite/
obj-$(CONFIG_VIDEO_EXYNOS)		+= fimc-is/
obj-$(CONFIG_VIDEO_EXYNOS_TV)		+= tv/

EXTRA_CLAGS += -Idrivers/media/video
